### ISSUE TITLE
Create file to download by ARGS or ENV

### ISSUE THREAD

**Issue by douglasresende** [douglasresende/spotify_downloader#1]
- Remove "Example code" into spotify.rb
- Create a file to download sending ARGS or ENV

 Example: 
```
PLAYLIST=37i9dQZF1DWTkIwO2HDifB ruby download.rb 
```
or
```
ruby download.rb 37i9dQZF1DWTkIwO2HDifB
```

**Comment by juneira** [comment]
Pull request related to this issue. https://github.com/douglasresende/spotify_downloader/pull/6
